### ISSUE TITLE
Values in platforms analysis plot sum up to more than 100%

### ISSUE THREAD

**Issue by aabarug** [scRNA-tools/scRNA-tools#223]
Hi folks! Thank you for the awesome resource! I've just noticed a bug on the analysis page - the platform plot doesn't seem to be displaying the correct percent values. I've attached a plot I downloaded today from the site:

![newplot(2)](https://user-images.githubusercontent.com/12524534/198191767-d8eb1f70-6f22-479a-9b7b-fdf46bb9181a.png)

That'll tally up to 117.7%

**Comment by lazappi** [comment]
Hi @aabarug, thanks for your interest in scRNA-tools 🎉! This is actually correct, it's just a bit unintuitive. The reason is that tools can be assigned to more than one platform (for example R packages that include C++ code) so when you sum up the percentages for each individual platform they come to more than 100%.

**Comment by aabarug** [comment]
Ah sweet! Thank you for that explanation. I was about to use that figure in a presentation and was like, wait those numbers don’t look right

**Comment by lazappi** [comment]
👍🏻 No probs
